variable "gitlab_runner_name" {}
variable "gitlab_runner_url" {}
variable "gitlab_runner_token" {}
variable "gitlab_runner_tags" {}
variable "gitlab_runner_docker_image" {}
variable "gitlab_concurrent_job" {}
variable "gitlab_check_interval" {}
variable "gitlab_rct_low_free_space" {}
variable "gitlab_rct_expected_free_space" {}
variable "gitlab_rct_low_free_files_count" {}
variable "gitlab_rct_expected_free_files_count" {}
variable "gitlab_rct_default_ttl" {}
variable "gitlab_rct_use_df" {}
variable "vpc_id" {}
variable "security_group_id" {}
variable "aws_access_key" {}
variable "aws_secret_key" {}
variable "key_name" {}