variable "gitlab_runner_url" {}
variable "gitlab_runner_token" {}
variable "gitlab_runner_tags" {}
variable "gitlab_runner_docker_image" {}
variable "vpc_id" {}
variable "security_group_id" {}
variable "aws_access_key" {}
variable "aws_secret_key" {}
variable "ssh_key_name" {}